// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANQq5hH1-yX_jiqqMmqRcCzEGWJ1JFnWE',
    appId: '1:941804631681:web:6ed0be3b818f34a32d3f80',
    messagingSenderId: '941804631681',
    projectId: 'sportsboard-d48ae',
    authDomain: 'sportsboard-d48ae.firebaseapp.com',
    storageBucket: 'sportsboard-d48ae.firebasestorage.app',
    measurementId: 'G-211TNVGXL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZfUr4-nAZDyeKyhkdAgSbNbPFkQ4Y1xI',
    appId: '1:941804631681:android:dfa08b9bebd0b4072d3f80',
    messagingSenderId: '941804631681',
    projectId: 'sportsboard-d48ae',
    storageBucket: 'sportsboard-d48ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVEgxNlPBmonh3s30bLBaGwpLhrZKDyuc',
    appId: '1:941804631681:ios:891f74b6b3bd1d852d3f80',
    messagingSenderId: '941804631681',
    projectId: 'sportsboard-d48ae',
    storageBucket: 'sportsboard-d48ae.firebasestorage.app',
    iosBundleId: 'com.example.sportsboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANQq5hH1-yX_jiqqMmqRcCzEGWJ1JFnWE',
    appId: '1:941804631681:web:cd1542da8fc93d342d3f80',
    messagingSenderId: '941804631681',
    projectId: 'sportsboard-d48ae',
    authDomain: 'sportsboard-d48ae.firebaseapp.com',
    storageBucket: 'sportsboard-d48ae.firebasestorage.app',
    measurementId: 'G-0QKGJ4Q3YX',
  );
}
